# Generated by Django 4.1.5 on 2023-01-11 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('numb', models.CharField(max_length=64, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obl', models.CharField(choices=[('22', 'Алтайский край'), ('28', 'Амурская область'), ('29', 'Архангельская область'), ('30', 'Астраханская область'), ('31', 'Белгородская область'), ('32', 'Брянская область'), ('33', 'Владимирская область'), ('34', 'Волгоградская область'), ('35', 'Вологодская область'), ('36', 'Воронежская область'), ('93', 'Донецкая Народная Республика'), ('79', 'Еврейская автономная область'), ('75', 'Забайкальский край'), ('90', 'Запорожская область'), ('37', 'Ивановская область'), ('99', 'Иные территории,включая город и космодром Байконур'), ('38', 'Иркутская область'), ('7', 'Кабардино-Балкарская Республика'), ('39', 'Калининградская область'), ('40', 'Калужская область'), ('41', 'Камчатский край'), ('9', 'Карачаево-Черкесская Республика'), ('42', 'Кемеровская область — Кузбасс'), ('43', 'Кировская область'), ('44', 'Костромская область'), ('23', 'Краснодарский край'), ('24', 'Красноярский край'), ('45', 'Курганская область'), ('46', 'Курская область'), ('47', 'Ленинградская область'), ('48', 'Липецкая область'), ('94', 'Луганская Народная Республика'), ('49', 'Магаданская область'), ('77', 'Москва'), ('50', 'Московская область'), ('51', 'Мурманская область'), ('83', 'Ненецкий автономный округ'), ('52', 'Нижегородская область'), ('53', 'Новгородская область'), ('54', 'Новосибирская область'), ('55', 'Омская область'), ('56', 'Оренбургская область'), ('57', 'Орловская область'), ('58', 'Пензенская область'), ('59', 'Пермский край'), ('25', 'Приморский край'), ('60', 'Псковская область'), ('1', 'Республика Адыгея (Адыгея)'), ('4', 'Республика Алтай'), ('2', 'Республика Башкортостан'), ('3', 'Республика Бурятия'), ('5', 'Республика Дагестан'), ('6', 'Республика Ингушетия'), ('8', 'Республика Калмыкия'), ('10', 'Республика Карелия'), ('11', 'Республика Коми'), ('91', 'Республика Крым'), ('12', 'Республика Марий Эл'), ('13', 'Республика Мордовия'), ('14', 'Республика Саха (Якутия)'), ('15', 'Республика Северная Осетия — Алания'), ('16', 'Республика Татарстан (Татарстан)'), ('17', 'Республика Тыва'), ('19', 'Республика Хакасия'), ('61', 'Ростовская область'), ('62', 'Рязанская область'), ('63', 'Самарская область'), ('78', 'Санкт-Петербург'), ('64', 'Саратовская область'), ('65', 'Сахалинская область'), ('66', 'Свердловская область'), ('92', 'Севастополь'), ('67', 'Смоленская область'), ('26', 'Ставропольский край'), ('68', 'Тамбовская область'), ('69', 'Тверская область'), ('70', 'Томская область'), ('71', 'Тульская область'), ('72', 'Тюменская область'), ('18', 'Удмуртская Республика'), ('73', 'Ульяновская область'), ('27', 'Хабаровский край'), ('86', 'Ханты-Мансийский автономный округ — Югра'), ('95', 'Херсонская область'), ('74', 'Челябинская область'), ('20', 'Чеченская Республика'), ('21', 'Чувашская Республика — Чувашия'), ('87', 'Чукотский автономный округ'), ('89', 'Ямало-Ненецкий автономный округ'), ('76', 'Ярославская область')], default='24', max_length=255, verbose_name='Регион')),
                ('name', models.CharField(max_length=128, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq', models.FloatField(verbose_name='Площадь')),
                ('rent_tax', models.PositiveIntegerField(verbose_name='Арендная ставка')),
                ('act_reg', models.BooleanField(default=False, verbose_name='Регистрация с актом/без')),
                ('mfc', models.CharField(choices=[('1', 'МФЦ'), ('2', 'ЭЦП')], max_length=10, verbose_name='ЭЦП/МФЦ')),
                ('vis', models.DateField(verbose_name='Подписан дата')),
                ('accept', models.DateField(verbose_name='Принят дата')),
                ('app_send_man', models.DateField(verbose_name='АПП отдал менеджеру')),
                ('app_send_sopr', models.DateField(verbose_name='АПП отдал сопроводителю')),
                ('afz_send_man', models.DateField(verbose_name='АФЗ отдал менеджеру')),
                ('afz_send_sopr', models.DateField(verbose_name='АФЗ отдал сопроводителю')),
                ('vis_buid', models.DateField(verbose_name='Стройка подписана')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('vis_bool', models.BooleanField(default=False, verbose_name='Подписан')),
                ('approve', models.BooleanField(default=False, verbose_name='Принят')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.address', verbose_name='Адрес')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.city', verbose_name='Город'),
        ),
    ]
