# Generated by Django 4.1.5 on 2023-01-14 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 14, 7, 41, 9, 81141, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.URLField(default='ya.ru'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='accept',
            field=models.DateField(blank=True, verbose_name='Принят дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='afz_send_man',
            field=models.DateField(blank=True, verbose_name='АФЗ отдал менеджеру'),
        ),
        migrations.AlterField(
            model_name='project',
            name='afz_send_sopr',
            field=models.DateField(blank=True, verbose_name='АФЗ отдал сопроводителю'),
        ),
        migrations.AlterField(
            model_name='project',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_send_man',
            field=models.DateField(blank=True, verbose_name='АПП отдал менеджеру'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_send_sopr',
            field=models.DateField(blank=True, verbose_name='АПП отдал сопроводителю'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mfc',
            field=models.CharField(blank=True, choices=[('1', 'МФЦ'), ('2', 'ЭЦП')], max_length=10, verbose_name='ЭЦП/МФЦ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vis',
            field=models.DateField(blank=True, verbose_name='Подписан дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vis_buid',
            field=models.DateField(blank=True, verbose_name='Стройка подписана'),
        ),
    ]
