# Generated by Django 4.1.5 on 2023-01-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_city_population_alter_project_file_projectdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sq',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Площадь'),
        ),
    ]
