# Generated by Django 4.1.5 on 2023-01-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_project_sq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accept',
            field=models.DateField(blank=True, null=True, verbose_name='Принят дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='afz_send_man',
            field=models.DateField(blank=True, null=True, verbose_name='АФЗ отдал менеджеру'),
        ),
        migrations.AlterField(
            model_name='project',
            name='afz_send_sopr',
            field=models.DateField(blank=True, null=True, verbose_name='АФЗ отдал сопроводителю'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_send_man',
            field=models.DateField(blank=True, null=True, verbose_name='АПП отдал менеджеру'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_send_sopr',
            field=models.DateField(blank=True, null=True, verbose_name='АПП отдал сопроводителю'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vis',
            field=models.DateField(blank=True, null=True, verbose_name='Подписан дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vis_buid',
            field=models.DateField(blank=True, null=True, verbose_name='Стройка подписана'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='Проект'),
        ),
    ]
