# Generated by Django 4.1.5 on 2023-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_address_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='delay_len',
            field=models.CharField(blank=True, max_length=255, verbose_name='Длительность отсрочки'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='len_rent',
            field=models.SmallIntegerField(blank=True, verbose_name='Максимальный срок аренды'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='radius_len',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Расстояние до учереждения'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='repair',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ремонт или отсрочка'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='sq_basemant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь подвала'),
        ),
    ]
