# Generated by Django 4.1.5 on 2023-01-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_projectdetail_len_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='ads_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обьявление'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий сотрудника по объекту(если есть)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='delay_len',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность отсрочки'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='radius_len',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Расстояние до учереждения'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='repair',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ремонт или отсрочка'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме SV(Развития)'),
        ),
    ]
